name: recb
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=2.18.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  torch_light: ^1.0.0
  flutter_settings_screens: ^0.2.2+1
  cupertino_icons: ^1.0.2
  firebase_core: ^2.1.0
  cloud_firestore: ^4.0.2
  file_picker: ^5.2.2
  image_picker: ^0.8.6
  google_fonts: ^3.0.1
  webview_flutter: ^3.0.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0



flutter:
  uses-material-design: true
  assets:
   - images/
  #   - images/a_dot_ham.jpeg


  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
